package com.smm.po;

import java.util.Date;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import com.smm.validation.ValidGroup1;

public class Item {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.id
     *
     * @mbg.generated Wed Jan 04 08:57:35 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.name
     *
     * @mbg.generated Wed Jan 04 08:57:35 CST 2017
     */
    //校验名称在1-30个字符之间
    //message是提示校验出错显示的信息
    //groups:此校验属于哪个分组，可以定义多个分组
    @Size(min=1,max=30,message="{item.name.length.error}",groups={ValidGroup1.class})
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.price
     *
     * @mbg.generated Wed Jan 04 08:57:35 CST 2017
     */
    private Double price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.detail
     *
     * @mbg.generated Wed Jan 04 08:57:35 CST 2017
     */
    private String detail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.createtime
     *
     * @mbg.generated Wed Jan 04 08:57:35 CST 2017
     */
    @NotNull(message="{item.createtime.isNull}")
    private Date createtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.id
     *
     * @return the value of item.id
     *
     * @mbg.generated Wed Jan 04 08:57:35 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.id
     *
     * @param id the value for item.id
     *
     * @mbg.generated Wed Jan 04 08:57:35 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.name
     *
     * @return the value of item.name
     *
     * @mbg.generated Wed Jan 04 08:57:35 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.name
     *
     * @param name the value for item.name
     *
     * @mbg.generated Wed Jan 04 08:57:35 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.price
     *
     * @return the value of item.price
     *
     * @mbg.generated Wed Jan 04 08:57:35 CST 2017
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.price
     *
     * @param price the value for item.price
     *
     * @mbg.generated Wed Jan 04 08:57:35 CST 2017
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.detail
     *
     * @return the value of item.detail
     *
     * @mbg.generated Wed Jan 04 08:57:35 CST 2017
     */
    public String getDetail() {
        return detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.detail
     *
     * @param detail the value for item.detail
     *
     * @mbg.generated Wed Jan 04 08:57:35 CST 2017
     */
    public void setDetail(String detail) {
        this.detail = detail == null ? null : detail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.createtime
     *
     * @return the value of item.createtime
     *
     * @mbg.generated Wed Jan 04 08:57:35 CST 2017
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.createtime
     *
     * @param createtime the value for item.createtime
     *
     * @mbg.generated Wed Jan 04 08:57:35 CST 2017
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
}