package com.smm.po;

public class Orderdetail {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderdetail.id
     *
     * @mbg.generated Wed Jan 04 08:57:35 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderdetail.order_id
     *
     * @mbg.generated Wed Jan 04 08:57:35 CST 2017
     */
    private Integer orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderdetail.item_id
     *
     * @mbg.generated Wed Jan 04 08:57:35 CST 2017
     */
    private Integer itemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderdetail.count_buy
     *
     * @mbg.generated Wed Jan 04 08:57:35 CST 2017
     */
    private Integer countBuy;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderdetail.id
     *
     * @return the value of orderdetail.id
     *
     * @mbg.generated Wed Jan 04 08:57:35 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderdetail.id
     *
     * @param id the value for orderdetail.id
     *
     * @mbg.generated Wed Jan 04 08:57:35 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderdetail.order_id
     *
     * @return the value of orderdetail.order_id
     *
     * @mbg.generated Wed Jan 04 08:57:35 CST 2017
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderdetail.order_id
     *
     * @param orderId the value for orderdetail.order_id
     *
     * @mbg.generated Wed Jan 04 08:57:35 CST 2017
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderdetail.item_id
     *
     * @return the value of orderdetail.item_id
     *
     * @mbg.generated Wed Jan 04 08:57:35 CST 2017
     */
    public Integer getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderdetail.item_id
     *
     * @param itemId the value for orderdetail.item_id
     *
     * @mbg.generated Wed Jan 04 08:57:35 CST 2017
     */
    public void setItemId(Integer itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderdetail.count_buy
     *
     * @return the value of orderdetail.count_buy
     *
     * @mbg.generated Wed Jan 04 08:57:35 CST 2017
     */
    public Integer getCountBuy() {
        return countBuy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderdetail.count_buy
     *
     * @param countBuy the value for orderdetail.count_buy
     *
     * @mbg.generated Wed Jan 04 08:57:35 CST 2017
     */
    public void setCountBuy(Integer countBuy) {
        this.countBuy = countBuy;
    }
}